services:
  - type: web
    name: dirtfree-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false # Isko manual Render dashboard par dalna hoga
